services:
  service:
    image: iht
    platform: linux/arm64
    build:
      dockerfile: Dockerfile
      context: .
      target: runtime
      ssh:
        - default
      args:
        - "DOCKER_BUILDKIT=1"
    env_file:
      - private.env
    environment:
      - "IHT_DEBUG=false"
      - "DEBUG=false"
      - "IHT_LOCAL=true"
      - "IHT_REALM=local"
      - "IHT_TEAM=system-resiliency"
      - "OTEL_EXPORTER_OTLP_ENDPOINT=http://dd-agent:4317"
      - "OTEL_METRIC_EXPORT_INTERVAL=5000"
    depends_on:
      dd-agent:
        condition: service_started

  service-test:
    image: iht-test
    platform: linux/arm64
    build:
      target: builder
      dockerfile: Dockerfile
      context: .
      ssh:
        - default
      args:
        - "DOCKER_BUILDKIT=1"
    env_file:
      - private.env
    entrypoint:
      - go
      - test
      - ./...
      - -covermode=atomic
      - -coverprofile
      - cover.out
      - 2>&1
      - |
      - go-junit-report
      - -set-exit-code
      - |
      - tee
      - report.xml

  # generate mock_utilities and persist them to outside folder structure
  # prereq: mockgen installed and GOPATH is in environment
  go-generate:
    tty: true
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: .
      target: builder
      ssh:
        - default
      args:
        - "DOCKER_BUILDKIT=1"
    entrypoint: ""
    volumes:
      - "./test/:/app/test/"
      - "go-modules:/.go/pkg/mod"
    command:
      - "sh"
      - "-c"
      - "rm -rf /app/test/mocks/ &&
        go generate -v /app/..."

  dd-agent:
    image: public.ecr.aws/datadog/agent
    volumes:
      - ./tests/data/datadog.yaml:/etc/datadog-agent/datadog.yaml
    ports:
      - 4317:4317
      - 4318:4318
    env_file:
      - private.env

volumes:
  go-modules:
    driver: local
